// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "RidusM",
            "email": "stormkillpeople@gmail.com"
        },
        "license": {
            "name": "MIT-0",
            "url": "https://github.com/aws/mit-0"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/notify": {
            "post": {
                "description": "Планирует отправку уведомления на указанное время",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Notification"
                ],
                "summary": "Создать уведомление",
                "parameters": [
                    {
                        "description": "Данные уведомления",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httpt.CreateNotificationRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Уведомление создано",
                        "schema": {
                            "$ref": "#/definitions/httpt.CreateNotificationResponse"
                        }
                    },
                    "400": {
                        "description": "Ошибка валидации",
                        "schema": {
                            "$ref": "#/definitions/httpt.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка",
                        "schema": {
                            "$ref": "#/definitions/httpt.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/notify/{id}": {
            "get": {
                "description": "Возвращает статус уведомления по уникальному идентификатору",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Notification"
                ],
                "summary": "Получить статус уведомления",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Уникальный идентификатор уведомления",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешный ответ с статусом уведомления",
                        "schema": {
                            "$ref": "#/definitions/httpt.NotificationStatusResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат notify_id",
                        "schema": {
                            "$ref": "#/definitions/httpt.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Уведомление не найдено",
                        "schema": {
                            "$ref": "#/definitions/httpt.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/httpt.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Отменяет запланированное уведомление",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Notification"
                ],
                "summary": "Отменить уведомление",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Уникальный идентификатор уведомления",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешный ответ",
                        "schema": {
                            "$ref": "#/definitions/httpt.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат notify_id",
                        "schema": {
                            "$ref": "#/definitions/httpt.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Уведомление не найдено",
                        "schema": {
                            "$ref": "#/definitions/httpt.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Уведомление уже отправлено или отменено",
                        "schema": {
                            "$ref": "#/definitions/httpt.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/httpt.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "httpt.CreateNotificationRequest": {
            "type": "object",
            "properties": {
                "channel": {
                    "type": "string",
                    "example": "email"
                },
                "payload": {
                    "type": "string",
                    "example": "Your order #123 is ready!"
                },
                "recipient": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "scheduled_at": {
                    "type": "string",
                    "example": "2023-10-27T10:00:00Z"
                }
            }
        },
        "httpt.CreateNotificationResponse": {
            "type": "object",
            "properties": {
                "channel": {
                    "type": "string",
                    "example": "email"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440001"
                },
                "message": {
                    "type": "string",
                    "example": "Notification created successfully"
                },
                "payload": {
                    "type": "string",
                    "example": "Your order #123 is ready!"
                },
                "recipient": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "scheduled_at": {
                    "type": "string",
                    "example": "2023-10-27T10:00:00Z"
                },
                "user_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "httpt.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "not_found"
                },
                "details": {
                    "type": "string",
                    "example": "notification with id 123 does not exist"
                },
                "error": {
                    "type": "string",
                    "example": "notification not found"
                }
            }
        },
        "httpt.NotificationStatusResponse": {
            "type": "object",
            "properties": {
                "channel": {
                    "type": "string",
                    "example": "EMAIL"
                },
                "created_at": {
                    "type": "string",
                    "example": "2023-10-26T10:00:00Z"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440001"
                },
                "last_error": {
                    "type": "string",
                    "example": "connection timeout"
                },
                "payload": {
                    "type": "string",
                    "example": "Your order #123 is ready!"
                },
                "retry_count": {
                    "type": "integer",
                    "example": 1
                },
                "scheduled_at": {
                    "type": "string",
                    "example": "2023-10-27T10:00:00Z"
                },
                "sent_at": {
                    "type": "string",
                    "example": "2023-10-27T10:00:05Z"
                },
                "status": {
                    "type": "string",
                    "example": "waiting"
                },
                "user_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "httpt.SuccessResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Notification cancelled successfully"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Notification Service API",
	Description:      "API для работы с уведомлениями",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
